local H = require("harness")

H.describe("Zettelkasten Plugin Loading", function()
  H.it("loads the zettelkasten module without error", function()
    H.assert_no_error(function()
      require("zettelkasten")
    end, "require zettelkasten")
  end)

  H.it("module returns a table with expected functions", function()
    local zk = require("zettelkasten")
    H.assert_eq(type(zk), "table", "module type")
    H.assert_eq(type(zk.setup), "function", "setup is function")
    H.assert_eq(type(zk.add_entry), "function", "add_entry is function")
    H.assert_eq(type(zk.search_entries), "function", "search_entries is function")
    H.assert_eq(type(zk.get_date), "function", "get_date is function")
    H.assert_eq(type(zk.is_valid_tag), "function", "is_valid_tag is function")
    H.assert_eq(type(zk.parse_header_tags), "function", "parse_header_tags is function")
    H.assert_eq(type(zk.parse_entries), "function", "parse_entries is function")
    H.assert_eq(type(zk.collect_tags), "function", "collect_tags is function")
    H.assert_eq(type(zk.filter_entries_by_tags), "function", "filter_entries_by_tags is function")
    H.assert_eq(type(zk.format_entry), "function", "format_entry is function")
  end)

  H.it("guard variable is set after plugin/ sourcing", function()
    H.assert_eq(vim.g.loaded_zettelkasten, true, "loaded guard variable")
  end)
end)

H.finish()
